name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '18'

            - name: Install dependencies
              run: |
                npm install

            - name: Run tests
              run: |
                npm test
            
            - name: Basic app check
              run: node --check app.js

    docker:
        needs: tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Set short SHA
              id: vars
              run: echo "SHORT_SHA=${GITHUB_SHA::3}" >> $GITHUB_ENV

            - name: Build and push Docker image
              uses: docker/build-push-action@v6
              with:
                context: .
                push: true
                platforms: linux/amd64
                tags: |
                  milorad86/devops-docker-app:latest
                  milorad86/devops-docker-app:${{ env.SHORT_SHA }}

    deploy:
        needs: docker
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Copy docker-compose.yml to server
              uses: appleboy/scp-action@master
              with:
                host: ${{ secrets.DROPLET_HOST }}
                username: ${{ secrets.DROPLET_USER }}
                key: ${{ secrets.DROPLET_SSH_KEY }}
                port: 22
                source: "/Users/miloradmarkovic/devops-docker-app/docker-compose.yaml"
                target: "~/docker-compose.yaml"
            - name: Execute deployment script on Droplet
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.DROPLET_HOST }}
                username: ${{ secrets.DROPLET_USER }}
                key: ${{ secrets.DROPLET_SSH_KEY }}
                port: 22
                script: |
                      cd ~
                      docker-compose pull
                      docker-compose down
                      docker-compose up -d
            
    